server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: payment_routh #payment_route #路由的ID，没有固定规则，但是要求统一，建议配合服务名称
          uri: http://localhost:8001  #匹配成功后提供服务的路由地址
          predicates:
            - Path=/payment/get/**   #断言，路径相匹配的才进行路由

eureka:
  instance:
    hostname: cloud-gateway-service
  client: ##服务提供者provider注册进eureka服务列表内
    fetch-registry: true #是否从Eureka Server 抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合 ribbon使用负载均衡
    register-with-eureka: true #表示是否将自己注册到 Eureka Server中，默认是true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka