server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名称进行路由
      routes:
        - id: payment_routh #payment_route #路由的ID，没有固定规则，但是要求统一，建议配合服务名称
#          uri: http://localhost:8001  #匹配成功后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE  #匹配成功后提供服务的路由地址，这个采用的微服务的注册中心中服务的名称，实现动态路由
          predicates:
            - Path=/payment/get/**   #断言，路径相匹配的才进行路由
            - After=2020-12-06T21:10:48.866+08:00[Asia/Shanghai] #请求必须是在这个时间之后才能生效
#            - Cookie=username,leehq
#            - Header=X-Request-Id,\d+ #请求头中要有属性:X-Request-Id，并且属性的值要满足值为整数的正则表达式。
#            - Host=**.atguigu.com
#            - Method=GET
#            - Query=username,\d+ #要含有参数username，并且参数的值整数，才能匹配路由
          filters:
            - AddRequestParameter=X-Request-Id,1024 #过滤器工厂会在匹配的请求头加上一对请求头，名称X-Request-Id,zhiwei 1024
eureka:
  instance:
    hostname: cloud-gateway-service
  client: ##服务提供者provider注册进eureka服务列表内
    fetch-registry: true #是否从Eureka Server 抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合 ribbon使用负载均衡
    register-with-eureka: true #表示是否将自己注册到 Eureka Server中，默认是true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka