server:
  port: 7001


eureka:
  instance:
    #eureka服务端的实例名称
    #hostname: localhost
    hostname: eureka7001.com
  client:
    register-with-eureka: false #false表示不向注册中心注册自己
    fetch-registry: false #false 表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      #设置与 Eureka Server 交互的 地址查询服务 和 注册服务都需要依赖这个地址。
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      #defaultZone: http://eureka7002.com:7002/eureka/ #集群时会指向其他 eureka。
      #单机版的，就是指向自己
      defaultZone: http://eureka7001.com:7001/eureka/
  server:
    #true表示开启 Eureka 的自我保护机制，false时表示关掉自我保护机制（保证不可用服务被及时剔除），默认是true(开启)
    enable-self-preservation: false
    # server清理无效节点的时间间隔，默认是60秒
    #eviction-interval-timer-in-ms: 2000
