server:
  port: 83

spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        # nacos 默认的端口号是8848
        server-addr: 127.0.0.1:8848

#消费者将要去访问的微服务名称，即成功注册进 nacos 的微服务提供者
service-url:
  nacos-user-service: http://nacos-payment-provider