server:
  port: 80

# 本项目是作为客户端验证测试 openfeign，所以就不再设置服务实例名称了

eureka:
  client:
    #表示是否将自己注册到 Eureka Server中，默认是true。本项目是作为客户端验证测试 openfeign，所以就不把它注册到Eureka中了
    register-with-eureka: false
    #是否从Eureka Server 抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合 ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #defaultZone: http://localhost:7001/eureka  单机版
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/ # 集群版

#设置Feign客户端超时时间（OpenFeign默认是支持Ribbon的）
ribbon:
  #建立连接所需要的时间，适用于网络状况正常的情况下，两端连接所需要的时间
  ReadTimeout: 5000
  #建立链接以后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000


logging:
  level:
    #feign日志以什么级别监控哪个接口，本例中是以debug的形式打印full级别的全日志
    com.atguigu.springcloud.service.PaymentFeignService: debug
