#8004表示注册到zookeeper服务器的支付服务提供者的端口号
server:
  port: 8004

spring:
  application:
    #服务器别名，注册到zookeeper注册中心的名称
    name: cloud-provider-payment
  cloud:
    zookeeper:
      connect-string: 192.168.43.18:2181